# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.api.room import room_pb2 as pb_dot_api_dot_room_dot_room__pb2


class RoomStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRoom = channel.unary_unary(
                '/api.room.Room/CreateRoom',
                request_serializer=pb_dot_api_dot_room_dot_room__pb2.CreateRoomRequest.SerializeToString,
                response_deserializer=pb_dot_api_dot_room_dot_room__pb2.CreateRoomResponse.FromString,
                _registered_method=True)
        self.GetRoom = channel.unary_unary(
                '/api.room.Room/GetRoom',
                request_serializer=pb_dot_api_dot_room_dot_room__pb2.GetRoomRequest.SerializeToString,
                response_deserializer=pb_dot_api_dot_room_dot_room__pb2.GetRoomResponse.FromString,
                _registered_method=True)
        self.ListRooms = channel.unary_unary(
                '/api.room.Room/ListRooms',
                request_serializer=pb_dot_api_dot_room_dot_room__pb2.ListRoomsRequest.SerializeToString,
                response_deserializer=pb_dot_api_dot_room_dot_room__pb2.ListRoomsResponse.FromString,
                _registered_method=True)
        self.LoadHistory = channel.unary_unary(
                '/api.room.Room/LoadHistory',
                request_serializer=pb_dot_api_dot_room_dot_room__pb2.LoadHistoryRequest.SerializeToString,
                response_deserializer=pb_dot_api_dot_room_dot_room__pb2.LoadHistoryResponse.FromString,
                _registered_method=True)
        self.RoomSession = channel.stream_stream(
                '/api.room.Room/RoomSession',
                request_serializer=pb_dot_api_dot_room_dot_room__pb2.ClientMessage.SerializeToString,
                response_deserializer=pb_dot_api_dot_room_dot_room__pb2.ServerEvent.FromString,
                _registered_method=True)


class RoomServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateRoom(self, request, context):
        """Unary RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRooms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RoomSession(self, request_iterator, context):
        """Bidirectional streaming - main session
        One stream per room per user. JoinRoom must be the first ClientMessage.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoomServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRoom,
                    request_deserializer=pb_dot_api_dot_room_dot_room__pb2.CreateRoomRequest.FromString,
                    response_serializer=pb_dot_api_dot_room_dot_room__pb2.CreateRoomResponse.SerializeToString,
            ),
            'GetRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoom,
                    request_deserializer=pb_dot_api_dot_room_dot_room__pb2.GetRoomRequest.FromString,
                    response_serializer=pb_dot_api_dot_room_dot_room__pb2.GetRoomResponse.SerializeToString,
            ),
            'ListRooms': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRooms,
                    request_deserializer=pb_dot_api_dot_room_dot_room__pb2.ListRoomsRequest.FromString,
                    response_serializer=pb_dot_api_dot_room_dot_room__pb2.ListRoomsResponse.SerializeToString,
            ),
            'LoadHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadHistory,
                    request_deserializer=pb_dot_api_dot_room_dot_room__pb2.LoadHistoryRequest.FromString,
                    response_serializer=pb_dot_api_dot_room_dot_room__pb2.LoadHistoryResponse.SerializeToString,
            ),
            'RoomSession': grpc.stream_stream_rpc_method_handler(
                    servicer.RoomSession,
                    request_deserializer=pb_dot_api_dot_room_dot_room__pb2.ClientMessage.FromString,
                    response_serializer=pb_dot_api_dot_room_dot_room__pb2.ServerEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.room.Room', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.room.Room', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Room(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.room.Room/CreateRoom',
            pb_dot_api_dot_room_dot_room__pb2.CreateRoomRequest.SerializeToString,
            pb_dot_api_dot_room_dot_room__pb2.CreateRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.room.Room/GetRoom',
            pb_dot_api_dot_room_dot_room__pb2.GetRoomRequest.SerializeToString,
            pb_dot_api_dot_room_dot_room__pb2.GetRoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRooms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.room.Room/ListRooms',
            pb_dot_api_dot_room_dot_room__pb2.ListRoomsRequest.SerializeToString,
            pb_dot_api_dot_room_dot_room__pb2.ListRoomsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.room.Room/LoadHistory',
            pb_dot_api_dot_room_dot_room__pb2.LoadHistoryRequest.SerializeToString,
            pb_dot_api_dot_room_dot_room__pb2.LoadHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RoomSession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/api.room.Room/RoomSession',
            pb_dot_api_dot_room_dot_room__pb2.ClientMessage.SerializeToString,
            pb_dot_api_dot_room_dot_room__pb2.ServerEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
